spring.application.name=AtividadeSistemasDistribuidos
spring.datasource.url=jdbc:postgresql://localhost:5432/atividadesistemasdistribuidos
spring.datasource.username=joaopedro
spring.datasource.password=280205