spring.application.name=AtividadeSistemasDistribuidos
spring.datasource.url=jdbc:postgresql://localhost:5432/atividadesistemasdistribuidos
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}